default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: <%= ENV.fetch("PG_USER") %>
  password: <%= ENV.fetch("PG_PASSWORD") %>
  host: <%= ENV.fetch("PG_HOST") %>
  port: <%= ENV.fetch("PG_PORT") %>
  database: ordering_system_development

test:
  <<: *default
  username: <%= ENV.fetch("PG_USER") %>
  password: <%= ENV.fetch("PG_PASSWORD") %>
  host: <%= ENV.fetch("PG_HOST") %>
  port: <%= ENV.fetch("PG_PORT") %>
  database: ordering_system_test

production:
  primary: &primary_production
    <<: *default
    username: <%= ENV.fetch("PG_USER") %>
    password: <%= ENV.fetch("PG_PASSWORD") %>
    host: <%= ENV.fetch("PG_HOST") %>
    port: <%= ENV.fetch("PG_PORT") %>
    database: ordering_system_production
  cache:
    <<: *primary_production
    database: ordering_system_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: ordering_system_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: ordering_system_production_cable
    migrations_paths: db/cable_migrate